<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>PsToXbox</RootNamespace>
    <AssemblyName>PsToXbox</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.IO" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ViGEmBusSetup.exe" />
    <EmbeddedResource Include="HidHideSetup.exe" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HidSharp" Version="2.6.4" />
    <PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
  </ItemGroup>

</Project>
